aftermath_dict = {
18: 'Fan-fucking-tastic. It\'s fat times ahead, safe and secure. That thing that would make your life better? Oh, you got it, absolutely, and then some. And then some more. Enjoy it!',
17: 'Fan-fucking-tastic. It\'s fat times ahead, safe and secure. That thing that would make your life better? Oh, you got it, absolutely, and then some. And then some more. Enjoy it!',
16: 'Fan-fucking-tastic. It\'s fat times ahead, safe and secure. That thing that would make your life better? Oh, you got it, absolutely, and then some. And then some more. Enjoy it!',
15: 'Fan-fucking-tastic. It\'s fat times ahead, safe and secure. That thing that would make your life better? Oh, you got it, absolutely, and then some. And then some more. Enjoy it!',
14: 'Fan-fucking-tastic. It\'s fat times ahead, safe and secure. That thing that would make your life better? Oh, you got it, absolutely, and then some. And then some more. Enjoy it!',
13: 'Fan-fucking-tastic. It\'s fat times ahead, safe and secure. That thing that would make your life better? Oh, you got it, absolutely, and then some. And then some more. Enjoy it!',
12: 'Not too shabby. You\'ve made it out with your dignity intact, through some fluke. There might even be a little profit, or self respect, or something. Time to throw a little party for all your friends.',
11: 'Not too shabby. You\'ve made it out with your dignity intact, through some fluke. There might even be a little profit, or self respect, or something. Time to throw a little party for all your friends.',
10: 'Not too shabby. You\'ve made it out with your dignity intact, through some fluke. There might even be a little profit, or self respect, or something. Time to throw a little party for all your friends.',
9: 'Nothing to crow about. Not better, but not way worse, either. Maybe the car is wrecked, or your spouse is leaving you, or there\'s a court date. But compared to some of the other people you know...',
8: 'Nothing to crow about. Not better, but not way worse, either. Maybe the car is wrecked, or your spouse is leaving you, or there\'s a court date. But compared to some of the other people you know...',
7: 'Weak. Hey, you\'re busted, beat, and broke down, but at least you\'ve learned a lesson about human greed and frailty, right? it\'ll serve you well in prison, which is probably where you are headed.',
6: 'Weak. Hey, you\'re busted, beat, and broke down, but at least you\'ve learned a lesson about human greed and frailty, right? it\'ll serve you well in prison, which is probably where you are headed.',
5: 'Miserable. You are humiliated in a big, public way, and whatever reputation you once had is now in dirty pieces all around you. You\'ll never think of these days without a shudder of horror at your own aggressive stupidity.',
4: 'Bitter. You know what it\'s like to be utterly crushed, casually brought low, forced to eat your own words and stand mute and powerless before your enemies. They gloat, and you are helpless.',
3: 'Grim. The stress and trauma from your little adventure are going to haunt you forever - bits of your soul are destroyed and you are missing a piece or two. In a few years children are going to cry when you get to close. All your plans have ended in complete ruin.', 
2: 'Merciless. You might not be dead on the outside but you sure as hell are dead on the inside. The emotional or mental wounds you have suffered will never heal. The future is a brick wall.',
1: 'You are certainly dead, probably from a self inflicted wound. People you care about are also probably dead, maybe through your own stupid, ugly failure. To say that you fucked up is an insult to fucked-upedness. You have redefined the term.',
0: 'The worst thing in the universe. This probably doesn\'t include death, since death would be way better than whatever this is. Be creative and don\'t settle for the first "worst" thing that comes to mind - there\'s something darker, more awful, more wretched in there somewhere.',
-1: 'Horrible. You are probably dead. Other people, probably innocent people, are as well. There is no justice, there is no mercy, everything is utterly, painfully screwed and it all - all of it - your fault.',
-2: 'Brutal. Wounds that will never heal, for starters; stuff sawed off, blown off, or burned off on your way to grand, ignominious failure. Kiss whatever you care about goodbye. You may die, but you may not.',
-3: 'Harsh. Shit-in-a-bag harsh, a-lifetime-of-medication harsh. A big black cloud of hurt is going to rain all over you. The things you need to happen are not going to, simple as that.',
-4: 'Savage. Savage as in "something ins broken or mashed." Maybe you\'ve got a permanent limp and a bad reputation. Plus, you totally fail.',
-5: 'Rough. You are getting whipped like a rented mule, for started, and you will remember this episode for all your diminished day. The lesson you learn will be profound, lingering, and painful.',
-6: 'Pathetic. You\'ll suffer, oh dear God you will suffer, and everyone will know of your malfeasance, your stupidity, you lack of common sense and decency. You\'re probably going to be locked up, too.',
-7: 'Pathetic. You\'ll suffer, oh dear God you will suffer, and everyone will know of your malfeasance, your stupidity, you lack of common sense and decency. You\'re probably going to be locked up, too.',
-8: 'Nothing to write home about. Back to where you started. Maybe sore and broke, just like yesterday and tomorrow. You probably learned something though, like how to do it right next time. Next time...',
-9: 'Nothing to write home about. Back to where you started. Maybe sore and broke, just like yesterday and tomorrow. You probably learned something though, like how to do it right next time. Next time...',
-10: 'Pretty good. All things considered, you\'re coming out of this smelling like a rose. You\'re a little better off - maybe you got the girl, or maybe you just didn\'t get caught.',
-11: 'Pretty good. All things considered, you\'re coming out of this smelling like a rose. You\'re a little better off - maybe you got the girl, or maybe you just didn\'t get caught.',
-12: 'Pretty good. All things considered, you\'re coming out of this smelling like a rose. You\'re a little better off - maybe you got the girl, or maybe you just didn\'t get caught.',
-13: 'Awesome. Insanely great. You will emerge not only unscathed, but if there\'s a guy involved, he\'s dropping his drawers. You might even get rich off this caper, who knows? Time for a new ride.',
-14: 'Awesome. Insanely great. You will emerge not only unscathed, but if there\'s a guy involved, he\'s dropping his drawers. You might even get rich off this caper, who knows? Time for a new ride.',
-15: 'Awesome. Insanely great. You will emerge not only unscathed, but if there\'s a guy involved, he\'s dropping his drawers. You might even get rich off this caper, who knows? Time for a new ride.',
-16: 'Awesome. Insanely great. You will emerge not only unscathed, but if there\'s a guy involved, he\'s dropping his drawers. You might even get rich off this caper, who knows? Time for a new ride.',
-17: 'Awesome. Insanely great. You will emerge not only unscathed, but if there\'s a guy involved, he\'s dropping his drawers. You might even get rich off this caper, who knows? Time for a new ride.',
-18: 'Awesome. Insanely great. You will emerge not only unscathed, but if there\'s a guy involved, he\'s dropping his drawers. You might even get rich off this caper, who knows? Time for a new ride.'
}